scss:
  config_file: .scss-style.yml

ruby:
  config_file: .ruby-style.yml

# javascript:
#   ignore_file: .javascript_ignore

javascript:
  enabled: false

coffeescript:
  config_file: .coffeescript-style.json

fail_on_violations: true
