# Travis CI will consult .ruby-version in the root of the repository and use the
# indicated Ruby runtime
language: ruby
rvm:
- 2.2.2

# Make Travis CI to start the MongoDB service on boot
services:
  - mongodb

notifications:
  email: false

before_install:
  - sh -c 'if [ -n "$QMAKE" ]; then sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa && sudo apt-get update && sudo apt-get install libqt5webkit5-dev qtdeclarative5-dev; fi'

script: 
  - xvfb-run rake test
