#!/bin/sh

if [ "$1" == "" ] || [ "$2" == "" ]; then
    echo "access_key_id and secret_access_key must be provided"
    exit 1
fi
ACCESS_KEY_ID="$1"
SECRET_ACCESS_KEY="$2"
HOST=$(heroku config:get HOST)
echo "Setup S3"

VARS=$(rake deploy:setup_s3 access_key_id="${ACCESS_KEY_ID}" secret_access_key="${SECRET_ACCESS_KEY}" host="${HOST}")
arr=(${VARS//\\n/ })
AWS_ACCESS_KEY_ID="${arr[0]}"
AWS_SECRET_ACCESS_KEY="${arr[1]}"
APP_NAME="${arr[2]}"

echo "Setting s3 variables to heroku"
heroku config:set AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}" AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}" FOG_DIRECTORY="${APP_NAME}"
